### ISSUE TITLE
emojilist.json was not found when setting Mach-O Type to Static Library

### ISSUE THREAD

**Issue by denniskeithgaso** [maxoumime/emoji-data-ios#3]
I am trying to convert all frameworks in my app into a static library. However I encounter this problem.
'emojilist.json was not found'
Any help is very much appreciated. 
Thank You!

**Comment by sparga** [comment]
Static libraries cannot embed resources. You'll need to use a bundle [like this article](https://medium.com/@09mejohn/resource-bundles-in-ios-static-library-beba3070fafd) describe.
